version: '3.3'

services:
  nginx:
    image: nginx:1.19.3-alpine
    ports:
      - 80:80
      - 443:443
  parcel:
    depends_on:
      - nginx
    build: .
    ports:
      - 2020:2020
      - 2021:2021
    volumes:
      - ./src:/var/www/src
    command: npm run dev
